### ISSUE TITLE
Windows support (request)

### ISSUE THREAD

**Issue by CaiusTSM** [billsix/pyNuklear#10]
Hello, I was wondering if you would be willing take add windows support. How hard would it be to get it working? I would also be willing to help make it work.

**Comment by billsix** [comment]
Thank you for the suggestion and for the offer of help.

 Instead, I recommend that you use https://github.com/swistakm/pyimgui/ .  I have been doing so for my personal projects for a little while, as that project supports Windows, Linux, and Mac easily via pip. Dear IMGUI is also more featureful than nuklear, in my opinion.

The only complaint about their project that I have is that their demo code is not as explicit in Python as I would like.  with that said, the project looks to be solid, as I can manually port the c++ demos over to Python without much fuss, perhaps I will add better demo code for them.

For an example use of their code, take a look at their demos, or a small project I made 

https://github.com/billsix/modelviewprojection/blob/master/demo24/demo.py

Soon I will mark the readme on pyNuklear to show it's deprecated status.

Thank you for your suggestion, and I hope that the other project will work well for you.
