### ISSUE TITLE
PyPI Index for pip install.

### ISSUE THREAD

**Issue by Zephrym** [billsix/pyNuklear#4]
Hey, this could be a very nice package but your current distribution method is not venv compatible and you are missing your setup.py file. Without these implemented this package is more or less "un-usable" for other developers. (Hardcoding packages to PATH is a big no-no and makes your script break on systems without it in PATH compared to venv where it works out of the box). Freezing scripts to executables becomes very buggy as well if you rely on PATH dependencies.

This package would be a great addition to pip via [PyPI](https://pypi.org/). But in its current state the install process is very clunky / error prone to install and does not play nice with venv.

[pynk](https://github.com/nathanrw/nuklear-cffi) only supports python 2.7 so this is a unique package and immediate mode gui's like nuklear are really nice in python (and under-used due to lack of libraries).

### EDIT: Read below PyPI deployment will be much more effort due to your implementations

 Could you deploy this to PyPI?
setuptools deployment guide (newest and easiest)
https://pythonhosted.org/an_example_pypi_project/setuptools.html

distutils deployment guide (older)
 http://devarea.com/deploying-a-new-python-package-to-pypi/#.W9VeiZNKiUk

This would also allow people to install your package via package managers on IDEs (like PyCharm) for example. It can also automatically install third party packages you use if you are missing them. (fresh venv for example will not have numpy / OpenGL / etc. You can use setuptools to grab them for users to ensure no errors.)

I am sure contributions would happen as well if this was on the index

**Comment by Zephrym** [comment]
gonna fork this and give it a go fixing it on my own.

**Comment by Zephrym** [comment]
Oofta I should have investigated the code more before I posted that. You are more or less going to re-write this entire package for it to be useful. 

Edit: Explanations below

**Comment by Zephrym** [comment]
### Sorry for all the edits in advanced. Was doing this on phone throughout the day.

Stuff like this is all over the library. (let me ask you. Would you ever assign an entire include / using to a variable in C/ C++ / C#? (No... because you can't and for a good reason)... but that is what you just did.

this is a huge no-no
```
if hasattr(builtins, "NUKLEAR_PATH"):
    NUKLEAR_PATH = builtins.NUKLEAR_PATH
else:
    print("Nuklear shared library not found")
    sys.exit(1)
_nuklear = NUKLEAR_PATH
```
If you need to check if you are a library that is what ``` if __name__== "__main__": is for```
if you need to check if you have a library it throws ImportError for your traditional try/except block. I tend to avoid this as there are much better ways to implement package distribution but it is really not that bad to do here. I have never seen a worse idea for python tho and you really need to drop the C style approach here as it will limit you from sharing anything with anyone.

Also for the most parts classes are terrible to use in python unless its a wrapper or you are doing some pipeline from another language and want to mimic a class(which... is probably a wrapper lol) . You should treat your packages like a class. And your ```__init__.py``` as your constructor

if you want to alias you can do 
```
# src/main.py
import package as Package
>> package.py import started
>> package.py import ended

from package import doStuff as do_stuff
>> package.py import started
>> package.py import ended

# the same thing
Package.doStuff()
>> Did stuff!!!
package.do_stuff()
>> Did stuff!!!
```
```
# src/package/__init__.py

print("package.py import started")

def doStuff(): # PEP8 violation. Should be do_stuff This is however the one PEP8 rule you can ignore if you so choose to do so.
    print("Did stuff!!!")

print("package.py import ended")
```

Edit: Examples

**Comment by Zephrym** [comment]
### Sorry for all the edits in advanced. Was doing this on phone throughout the day.

Here is also what built-ins is for

_Override the default open function to also convert the output to upper-case whenever you call open_

``` 
# example from Zephrym for built-ins. Wrapper and Decorator example included.
import builtins


def open(path):
    """ Example doc-string
    
    Prints decorator called! and converts file output to upper-case
    
    :param path: path to file as str
    :return: our open file with the output as upper-case 
    """

    file = builtins.open(path, 'r')  # r = read
    return ExampleUpperCaseWrapper(file)


def example_decorator():
"""
 using inner scope functions and passing args is generally easier
 than initializing and implementing class methods in python
"""
    def _inner_scope_func_example(): 
        print("decorator called!")
    
    _inner_scope_func_example() # still in example_decorator scope. Calls the print


def arg_pass_example(arbitrary_arg):
    def _redundant_inner_def(arbitrary_arg):
        print(arbitrary_arg)
    _redundant_inner_def(arbitrary_arg) # print(arbitrary_arg)

class ExampleUpperCaseWrapper:
    '''Wrapper around a file that converts output to upper-case.'''

    def __init__(self, file):
        self._file = file

    @example_decorator
    def read(self, count = -1):
        return self._file.read(count).upper()

``` 
modified example from from https://docs.python.org/3/library/builtins.html



You more or less just implemented your own pyNuklear keywords into your local version of python and wonder why peoples "compilers" are not compatible with yours. Sure we can "hack" our interpreter and add you into path. But that is not how things are done with python and we have much better pipelines.

Edit: Examples

**Comment by billsix** [comment]
Thanks for the comments and help.  I'll try to fix the more egregious parts of my build process, and if you are able to fork it later and help, I would be very pleased.  I would like to distribute this project in the normal Python manner, of which I am unaccustomed.  I like your direct style of communication btw.

The builtins stuff was a hack I put in when I thought that, like nuklear itself, my nuklear.py would be rendering technology independent.  But as I am lazy, and do not care to use anything but glfw3, I can remove that hack.

Thanks for the links regarding python packaging.  Searching for relevant docs online has been tough, between pip, virtualenv, pipenv, wheels etc.  For a first time Python user such as myself, with only me working on the project, it's been quite daunting.  

I will autopep8 the code.

I used classes because I figured that
"nuklear.menu_begin_label(text="MENU",
                                        align=nk.TextAlign.TEXT_LEFT,
                                        size=nk.Vec2(120.0,200.0)):"

is more palatable to the average programmer than

"import nuklear as nk
  nk.menu_begin_label(context = nuklearContext,
                                   text="MENU",
                                   align=nk.TextAlign.TEXT_LEFT,
                                   size=nk.Vec2(120.0,200.0)):
"

**Comment by billsix** [comment]
I'm very close to getting this to work, I think, on the pipify branch.  https://github.com/billsix/pyNuklear/tree/pipify

I got a requirements.txt for "pip install -r requirements.txt", "python setup.py install" will compile the shared library and install it in my venv (although the .so and egg file is one directory higher than I would have expected). 

And I can't figure out how to reference the shared library in __init__.py, which I need so that the bindings call C.

Any chance that you can help me in finishing this Zephrym?

**Comment by Zephrym** [comment]
Sure I would be willing to help out.

Could you explain to me the purpose of `_nuklear = ctypes.CDLL("pynuklear")` ? I believe ffi is the better approach here
``` 
# part of https://raw.githubusercontent.com/nathanrw/nuklear-cffi/master/pynk/build.py


    # Now create the FFI builder.
    print "Creating ffi builder..."
    ffibuilder = cffi.FFI()
    ffibuilder.cdef(defs)
    ffibuilder.set_source("_nuklear", source, libraries=[])
    return ffibuilder
```
This will allow you to call your library via `from _nuklear import lib, ffi`

I believe the better approach here would be using https://pypi.org/project/cffi/
https://cffi.readthedocs.io/en/latest/cdef.html

I found these examples via https://github.com/nathanrw/nuklear-cffi/tree/master/pynk

**Comment by Zephrym** [comment]
On a side note my PyCharm did catch missing dependencies after your recent changes and was a breeze to get them. The class implementations are not really that big of a deal since this you might actually need them if you need to pass a context through like that. 

I am unfamiliar with Nuklear but it seems odd to me that you would need to pass context into it so I feel that is a quirk of some other implementation.

As for only supporting glfw3 that is completely fine to do and probably a smart approach. Changing that later on to add other renderers like pygame is not that big of a deal if you really would like to add it. glfw3 only is just fine for the vast majority if not all use cases though and PyGame as a renderer is more of just a preference for some people who are familiar with it.

**Comment by billsix** [comment]
After investigation, turns out that getting distutils to work with a shared library (which isn't a python module, it's just a shared library) is near impossible.

Will investigate wheels, but I haven't found good docs.

Seems to me I'll either need to figure out wheels, or ditch ctypes and rewrite everything using the python extension API.  Both of which should support pip.  The last option is to keep the build process as is, faults and all, with no pip support.

**Comment by Zephrym** [comment]
> After investigation, turns out that getting distutils to work with a shared library (which isn't a python module, it's just a shared library) is near impossible.
> 
> Will investigate wheels, but I haven't found good docs.
> 
> Seems to me I'll either need to figure out wheels, or ditch ctypes and rewrite everything using the python extension API. Both of which should support pip. The last option is to keep the build process as is, faults and all, with no pip support.

Have you taken a look at cffi? It seems to me that this is what you are trying to accomplish. You should be able to parse the nuklear source and then use it as a shared library via the cffi library (check https://github.com/billsix/pyNuklear/issues/4#issuecomment-434169848 for references)

**Comment by creikey** [comment]
@Zephrym Why did you close this issue?

**Comment by billsix** [comment]
pyNuklear is on Pypi now, please let me know if there are any issues.  I've only tested it on linux.

pip install pyNuklear
run Python
"import pynuklear.demo.glfw_opengl3 as gl3Demo
gl3Demo.demo()"

It's a source distribution requiring a C compiler.  If I can figure out how to get manylinux working, I would make a wheel.
